### ISSUE TITLE
Use sphinx-apidoc to create API docs fully automatic

### ISSUE THREAD

**Issue by kmuehlbauer** [vispy/vispy-website#15]
As issued in https://github.com/vispy/vispy/issues/113 API docs are generated by specifying some classes manually. This should be made fully automatic.

For instance in https://github.com/vispy/vispy-website/blob/master/visuals.rst only `filters` and `transforms` are referenced, but eg. `collections` is missing.

**Comment by djhoese** [comment]
The site now using `sphinxcontrib.apidoc` so this is done automatically now. Thanks.
