### ISSUE TITLE
There's a blank dropdown that shouldn't be in the menu bar

### ISSUE THREAD

**Issue by suzil** [vispy/vispy-website#20]
![screenshot-2018-2-15 home vispy](https://user-images.githubusercontent.com/13723264/36265536-b1398628-126f-11e8-89c1-a394125e36e0.png)

**Comment by suzil** [comment]
Issue is caused by the option in `conf.py`:
```python
'navbar_pagenav': True,
```
It's not really a bug because it seems like the theme was designed with this in mind. It makes sense on any page except for the index where it's a blank dropdown. I don't see an easy fix.

**It'd be nice if there was a way to hide this dropdown only on the homepage.**

**Comment by larsoner** [comment]
Agreed. This is thus really a bug with `Sphinx` then, right? If so feel free to open an upstream bug and close this one.

**Comment by djhoese** [comment]
Unless I'm missing something, this is still an issue.

**Comment by djhoese** [comment]
I've now completely redone the site (not deployed yet but merged in this repository) and we now use a new theme so this is no longer an issue.
