### ISSUE TITLE
Link to the book on modern Open GL doesn't work.

### ISSUE THREAD

**Issue by oppt-admin** [vispy/vispy-website#21]
Link is on the bottom of the page in the paragraph  **Learning Modern 3D Graphics Programming**

http://vispy.org/modern-gl.html

**Comment by djhoese** [comment]
I think this might be the new URL for it: https://paroj.github.io/gltut/

@larsoner @kmuehlbauer Anyone else remember what book this is supposed to reference?

**Comment by kmuehlbauer** [comment]
@davidh-ssec Your guess seems correct. I had a look at the link with the wayback machine. Same book.

**Comment by oppt-admin** [comment]
Thanks for the prompt follow up... and the link.

**Comment by djhoese** [comment]
This was done in #29 and will be deployed shortly.
