### ISSUE TITLE
Usage of non-free lena picture

### ISSUE THREAD

**Issue by ghisvail** [vispy/vispy-website#4]
The source tree contains an occurrence of the infamous Lena picture located at `_static/screenshots/gloo-lena.png`, which is considered [non-free](https://lintian.debian.org/tags/license-problem-non-free-img-lenna.html). Please consider replacing this image with a freely licensed alternative.

**Comment by astrofrog** [comment]
It's also generally a bad example to use (https://en.wikipedia.org/wiki/Lenna#Controversy) even if it was free, so I'm very much in favor of changing it.

**Comment by almarklein** [comment]
Big plus one for me. Skimage has adopted this as their standard image: https://raw.githubusercontent.com/imageio/imageio-binaries/master/images/astronaut.png

**Comment by larsoner** [comment]
In SciPy we went to using `face` and `ascent`:

http://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.misc.lena.html

@ghisvail do you have time to make another PR to correct it? Feel free to pick any of the aforementioned images you like.

**Comment by ghisvail** [comment]
I am on it
